#!/bin/sh
# This script tells chronyd that the connection is up so that it can
# contact the server.  John Hasler <jhasler@debian.org> 1998-2003
# Any possessor of a copy of this program may treat it as if it
# were in the public domain.  I waive all rights.
# Modified by Vincent Blut <vincent.debian@free.fr>

if [ -e /run/chrony/chronyd.pid ]; then
    chronyc onoffline > /dev/null 2>&1
fi

exit 0
