################################################################################
# General
################################################################################

# Top Ranking Group By Request
ranking_count = 40

# Top Slow Requests
slow_count = 37

# Show Standard Deviation column
show_stddev = true

# Show HTTP Status Code columns
show_status_code = true

# Show HTTP Response Bytes columns
show_bytes = true

# Percentiles
percentiles = [ 50.0, 90.0, 95.0, 99.0 ]

################################################################################
# Scale
################################################################################

# for Nginx($request_time)
scale = 0
effective_digit = 3

# for Apache(%D) and Varnishncsa(%D)
#scale = -6
#effective_digit = 6

# for H2O(%{duration}x)
#scale = 0
#effective_digit = 6

# for Envoy
#scale = -3
#effective_digit = 3

# for Rack(Rack::CommonLogger)
#scale = 0
#effective_digit = 4

################################################################################
# Parse
################################################################################

#
# combined + duration
# Nginx example: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
# Apache example: "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"
# H2O example: "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" %{duration}x"
# Varnishncsa example: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %D'
#
log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" ([0-9.]+)$'
request_index = 5
status_index = 6
bytes_index = 7
duration_index = 10

#
# Envoy example: use default format
#
#log_format = '^\[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) ([^ ]+) (\d+|-) (\d+|-) (\d+) (\d+) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)"'
#request_index = 2
#status_index = 3
#bytes_index = 6
#duration_index = 7

#
# Rack example: use Rack::CommonLogger, Logger.new("/tmp/app.log")
#
#log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) ([0-9.]+)$'
#request_index = 5
#status_index = 6
#bytes_index = 7
#duration_index = 8

################################################################################
# Bundle
################################################################################

#
# You can aggregate requests by regular expression
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#
[[bundle]]
regexp = '^POST /api/organizer/player/[^/]*/disqualified'
name = 'POST /api/organizer/player/:player_id/disqualified'

[[bundle]]
regexp = '^POST /api/organizer/competition/[^/]*/finish'
name = 'POST /api/organizer/competition/:competition_id/finish'

[[bundle]]
regexp = '^POST /api/organizer/competition/[^/]*/score'
name = 'POST /api/organizer/competition/:competition_id/score'

[[bundle]]
regexp = '^GET /api/player/player/[^ ]*'
name = 'GET /api/player/player/:player_id'

[[bundle]]
regexp = '^GET /api/player/competition/[^/]*/ranking'
name = 'GET /api/player/competition/:competition_id/ranking'

#[[bundle]]
#regexp = '^(GET|HEAD) /stylesheets/'
#name = 'GET /stylesheets/*'
#
#[[bundle]]
#regexp = '^(GET|HEAD) /images/'
#name = 'GET /images/*'

################################################################################
# Replace
################################################################################

#
# You can replace the part of urls which matched to your regular expressions.
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#
[[replace]]
regexp = '\?.*'
replace = '?querystring'
#
#[[replace]]
#regexp = '=[0-9]+(&|\s)'
#replace = '=<num>$1'
#
#[[replace]]
#regexp = '\s+HTTP/[0-9.]+$'
#replace = ''

################################################################################
